In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [101]:
df = pd.read_csv('Dataset_clean_f.csv')

In [102]:
df.head()

StartTime                    LastTime       Dur  \
0  2021-03-15 14:39:09.629944  2021-03-15 14:39:13.282923  3.652979   
1  2021-03-15 14:39:22.815682  2021-03-15 14:39:22.815974  0.000292   
2  2021-03-15 14:39:58.689698  2021-03-15 14:39:58.691416  0.001718   
3  2021-03-15 14:40:02.573542  2021-03-15 14:40:03.889095  1.315553   
4  2021-03-15 14:40:18.423558  2021-03-15 14:40:18.425145  0.001587   

       SrcAddr      DstAddr Proto  TotPkts  SrcPkts  DstPkts  TotBytes  ...  \
0  172.20.10.5  172.20.10.2   tcp       20       10       10      1839  ...   
1  172.20.10.5  172.20.10.2   tcp        4        2        2       478  ...   
2  172.20.10.5  172.20.10.2   tcp       12        6        6       884  ...   
3  172.20.10.5  172.20.10.2   tcp        8        4        4       958  ...   
4  172.20.10.5  172.20.10.2   tcp       12        6        6       886  ...   

       DstRate  State   SrcWin    DstWin    TcpRtt    SynAck    AckDat  hour  \
0     2.463743      1  64256.0  131456.0  0.000295  0.000175  0.000120    14   
1  3424.657471      1  64256.0  131328.0  0.000295  0.000175  0.000120    14   
2  2910.360840      1  64256.0  131648.0  0.000348  0.000121  0.000227    14   
3     2.280410      1  64256.0  131136.0  0.000295  0.000175  0.000120    14   
4  3150.598633      1  64256.0  131648.0  0.000250  0.000122  0.000128    14   

   min  class  
0   39    4.0  
1   39    4.0  
2   39    4.0  
3   40    4.0  
4   40    4.0  

[5 rows x 28 columns]

In [108]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6269 entries, 0 to 6268
Data columns (total 21 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   Dur       6269 non-null   float64
 1   TotPkts   6269 non-null   int64  
 2   SrcPkts   6269 non-null   int64  
 3   DstPkts   6269 non-null   int64  
 4   TotBytes  6269 non-null   int64  
 5   SrcBytes  6269 non-null   int64  
 6   Load      6269 non-null   float64
 7   Loss      6269 non-null   int64  
 8   SrcLoss   6269 non-null   int64  
 9   DstLoss   6269 non-null   int64  
 10  pLoss     6269 non-null   float64
 11  Rate      6269 non-null   float64
 12  SrcRate   6269 non-null   float64
 13  DstRate   6269 non-null   float64
 14  State     6269 non-null   int64  
 15  SrcWin    6269 non-null   float64
 16  DstWin    6269 non-null   float64
 17  TcpRtt    6269 non-null   float64
 18  SynAck    6269 non-null   float64
 19  AckDat    6269 non-null   float64
 20  class     6269 non-null   floa

# Decision Tree Classifier

In [109]:
from sklearn.model_selection import train_test_split

In [154]:
X = df.drop('class',axis=1)
y = df['class']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=101)

In [155]:
from sklearn.tree import DecisionTreeClassifier

In [156]:
dtree = DecisionTreeClassifier()

In [157]:
dtree.fit(X_train,y_train)

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                       max_depth=None, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=None, splitter='best')

In [158]:
predictions1 = dtree.predict(X_test)

In [159]:
from sklearn.metrics import classification_report,confusion_matrix

In [160]:
print(classification_report(y_test,predictions1))

              precision    recall  f1-score   support

         1.0       0.94      0.99      0.96       149
         2.0       0.99      0.99      0.99      1040
         3.0       0.93      0.84      0.88        91
         4.0       1.00      1.00      1.00       789

    accuracy                           0.99      2069
   macro avg       0.96      0.95      0.96      2069
weighted avg       0.99      0.99      0.99      2069



In [161]:
print(confusion_matrix(y_test,predictions1))

[[ 147    0    2    0]
 [   4 1032    4    0]
 [   6    9   76    0]
 [   0    0    0  789]]


In [162]:
from sklearn.metrics import confusion_matrix,accuracy_score
accuracy_score(y_test,predictions1)

0.9879168680521991

# Random Forest Classifier

In [121]:
df.head()

Dur  TotPkts  SrcPkts  DstPkts  TotBytes  SrcBytes          Load  \
0  3.652979       20       10       10      1839       943  3.626629e+03   
1  0.000292        4        2        2       478       239  6.575342e+06   
2  0.001718       12        6        6       884       467  3.436554e+06   
3  1.315553        8        4        4       958       479  4.378387e+03   
4  0.001587       12        6        6       886       469  3.725268e+06   

   Loss  SrcLoss  DstLoss  ...          Rate      SrcRate      DstRate  State  \
0     0        0        0  ...      5.201234     2.463743     2.463743      1   
1     0        0        0  ...  10273.972656  3424.657471  3424.657471      1   
2     0        0        0  ...   6402.793945  2910.360840  2910.360840      1   
3     0        0        0  ...      5.320957     2.280410     2.280410      1   
4     0        0        0  ...   6931.316895  3150.598633  3150.598633      1   

    SrcWin    DstWin    TcpRtt    SynAck    AckDat  class  
0  64256.0  131456.0  0.000295  0.000175  0.000120    4.0  
1  64256.0  131328.0  0.000295  0.000175  0.000120    4.0  
2  64256.0  131648.0  0.000348  0.000121  0.000227    4.0  
3  64256.0  131136.0  0.000295  0.000175  0.000120    4.0  
4  64256.0  131648.0  0.000250  0.000122  0.000128    4.0  

[5 rows x 21 columns]

In [163]:
from sklearn.ensemble import RandomForestClassifier

In [164]:
rfc = RandomForestClassifier(n_estimators=600)

In [165]:
rfc.fit(X_train,y_train)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=600,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [168]:
predictions2 = rfc.predict(X_test)

In [166]:
from sklearn.metrics import classification_report,confusion_matrix

In [169]:
print(classification_report(y_test,predictions2))

              precision    recall  f1-score   support

         1.0       0.93      0.99      0.96       149
         2.0       0.99      0.99      0.99      1040
         3.0       0.95      0.82      0.88        91
         4.0       1.00      1.00      1.00       789

    accuracy                           0.99      2069
   macro avg       0.97      0.95      0.96      2069
weighted avg       0.99      0.99      0.99      2069



In [170]:
print(confusion_matrix(y_test,predictions2))

[[ 147    0    2    0]
 [   4 1034    2    0]
 [   7    9   75    0]
 [   0    0    0  789]]


In [172]:
from sklearn.metrics import confusion_matrix,accuracy_score
accuracy_score(y_test,predictions2)

0.9884001933301112

# KNN

In [130]:
from sklearn.preprocessing import StandardScaler

In [131]:
scaler = StandardScaler()

In [132]:
scaler.fit(df.drop('class',axis=1))

StandardScaler(copy=True, with_mean=True, with_std=True)

In [133]:
scaled_features = scaler.transform(df.drop('class',axis=1))

In [134]:
df_feat = pd.DataFrame(scaled_features,columns=df.columns[:-1])
df_feat.head()

Dur   TotPkts   SrcPkts   DstPkts  TotBytes  SrcBytes      Load  \
0  2.064908  0.088798  0.073453  0.107294 -0.027997 -0.031359 -0.350528   
1 -0.474878 -0.094537 -0.092454 -0.096702 -0.049952 -0.046477  5.000353   
2 -0.473887 -0.002870 -0.009501  0.005296 -0.043403 -0.041581  2.444661   
3  0.439649 -0.048703 -0.050978 -0.045703 -0.042209 -0.041323 -0.349916   
4 -0.473978 -0.002870 -0.009501  0.005296 -0.043371 -0.041538  2.679740   

       Loss   SrcLoss   DstLoss     pLoss      Rate   SrcRate   DstRate  \
0 -0.197161 -0.191377 -0.194836 -0.205849 -0.417255 -0.377458 -0.374223   
1 -0.197161 -0.191377 -0.194836 -0.205849  2.586185  3.879826  3.884485   
2 -0.197161 -0.191377 -0.194836 -0.205849  1.453932  3.240030  3.244475   
3 -0.197161 -0.191377 -0.194836 -0.205849 -0.417220 -0.377686 -0.374452   
4 -0.197161 -0.191377 -0.194836 -0.205849  1.608515  3.538891  3.543436   

      State    SrcWin    DstWin    TcpRtt    SynAck    AckDat  
0 -0.888988 -0.273341  0.541902 -0.291851 -0.068873 -0.283484  
1 -0.888988 -0.273341  0.539536 -0.291851 -0.068873 -0.283484  
2 -0.888988 -0.273341  0.545451 -0.290900 -0.072881 -0.281508  
3 -0.888988 -0.273341  0.535987 -0.291851 -0.068873 -0.283484  
4 -0.888988 -0.273341  0.545451 -0.292658 -0.072807 -0.283337

In [135]:
X_train, X_test, y_train, y_test = train_test_split(scaled_features,df['class'],
                                                    test_size=0.30)

In [136]:
from sklearn.neighbors import KNeighborsClassifier

In [137]:
knn = KNeighborsClassifier(n_neighbors=1)

In [138]:
knn.fit(X_train,y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=1, p=2,
                     weights='uniform')

In [139]:
pred = knn.predict(X_test)

In [140]:
print(confusion_matrix(y_test,pred))

[[122   4   6   2]
 [  9 895   7   0]
 [  6   5  79   0]
 [  1   3   0 742]]


In [141]:
print(classification_report(y_test,pred))

              precision    recall  f1-score   support

         1.0       0.88      0.91      0.90       134
         2.0       0.99      0.98      0.98       911
         3.0       0.86      0.88      0.87        90
         4.0       1.00      0.99      1.00       746

    accuracy                           0.98      1881
   macro avg       0.93      0.94      0.94      1881
weighted avg       0.98      0.98      0.98      1881



In [142]:
accuracy_score(y_test,pred)

0.9771398192450824

# SVM

In [173]:
X_train, X_test, y_train, y_test = train_test_split(df, np.ravel(df['class']), test_size=0.30, random_state=101)

In [174]:
from sklearn.svm import SVC

In [175]:
model = SVC()

In [176]:
model.fit(X_train,y_train)

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [177]:
predictions3 = model.predict(X_test)

In [178]:
from sklearn.metrics import classification_report,confusion_matrix

In [179]:
print(confusion_matrix(y_test,predictions3))

[[ 97  37   0   0]
 [  0 947   0   0]
 [ 40  16   0  27]
 [  0  15   0 702]]


In [180]:
print(classification_report(y_test,predictions3))

              precision    recall  f1-score   support

         1.0       0.71      0.72      0.72       134
         2.0       0.93      1.00      0.97       947
         3.0       0.00      0.00      0.00        83
         4.0       0.96      0.98      0.97       717

    accuracy                           0.93      1881
   macro avg       0.65      0.68      0.66      1881
weighted avg       0.89      0.93      0.91      1881



/Users/alighannadrad/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [181]:
accuracy_score(y_test,predictions3)

0.9282296650717703

In [183]:
df1 = df.to_csv('Dataset_clean_final.csv')